config/routes.rb
Rails.application.routes.draw do
  devise_for :clients
  devise_scope :client do
    get '/clients/sign_out', to:'devise/sessions#destroy'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'new_reservation/:flight_id', to: 'reservation#new', as: :new_reservations
  post 'new_reservation/:flight_id', to: 'reservation#create', as: :new_reservation_creation
  get 'reservation_success/:id', to: 'reservation#success', as: :reservations
  delete 'reservation/:id', to: 'reservation#delete', as: :delete_reservations
  get 'reservation/history', to: 'reservation#history', as: :reservation_history
  root to: "home#index"
end

app/models/airport.rb
# frozen_string_literal: true

class Airport < ActiveRecord::Base
  has_many :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations
end

app/models/flight.rb
# frozen_string_literal: true

class Flight < ActiveRecord::Base
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :reservations
  def arrival
    return (departure + duration.minutes)
  end
end

app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ActiveRecord::Base
  belongs_to :flight
  belongs_to :client
  def category_name
    category == 0 ?  "First Class" : "Economy Class"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients/confirmations_controller.rb
# frozen_string_literal: true

class Clients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/clients/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Clients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/clients/passwords_controller.rb
# frozen_string_literal: true

class Clients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/clients/registrations_controller.rb
# frozen_string_literal: true

class Clients::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/clients/sessions_controller.rb
# frozen_string_literal: true

class Clients::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/clients/unlocks_controller.rb
# frozen_string_literal: true

class Clients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @flights = Flight.where('departure > ?', Time.now).paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/reservation_controller.rb
class ReservationController < ActionController::Base
  layout "application"
  before_action :authenticate_client!

  def create
    # Create a new reservation with the form data
    reservation = Reservation.new(reservation_params)
    reservation.client = current_client

    # Generate a unique alphanumeric reference for the reservation
    loop do
      reservation.pnr = SecureRandom.alphanumeric(6).upcase
      break unless Reservation.exists?(pnr: reservation.pnr)
    end

    if reservation.save
      # Send the confirmation email
      ReservationMailer.confirmation_email(reservation).deliver_now

      # Redirect to the success page
      redirect_to({ action: :success, id: reservation.id })
    else
      puts reservation.errors.messages
      # Handle errors (e.g. render the form again with error messages)
    end
  end
  def new
    @flight = Flight.find(params[:flight_id])
    @reservation = Reservation.new
  end

  def success
    @reservation = Reservation.find(params[:id])
  end

  def delete
    reservation = Reservation.find(params[:id])

    if reservation.client == current_client
      reservation.destroy
      # Redirect to a page indicating the reservation has been deleted
      flash["notice"] = "Booking deleted with great success !"
      redirect_to({ controller: :home, action: :index})
    else
      # Redirect to an error page or show an error message
      flash["notice"] = "Couldn't delete booking'((("
      redirect_to({ controller: :home, action: :index})
    end
  end

  def history
    @reservations = Reservation.where(client_id: current_client.id).paginate(page: params[:page], per_page: 10)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:flight_id, :category, :nb_seats)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/home/index.html.erb
<div class="row">
  <% @flights.each do |flight| %>
    <div class="col-md-4">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">Flight <%= flight.flight_company_id %></h5>
          <p class="card-text">
            Departure Airport: <%= flight.departure_airport.name %> (<%= flight.departure_airport.iata %>)<br>
            Arrival Airport: <%= flight.arrival_airport.name %> (<%= flight.arrival_airport.iata %>)<br>
            Departure Date and Hour: <%= flight.departure.strftime('%Y-%m-%d %H:%M') %><br>
            Arrival Date and Hour: <%= flight.arrival.strftime("%Y-%m-%d %H:%M")%>
          </p>
          <%= button_to 'Book', new_reservations_path(flight_id: flight.id), method: :get, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @flights %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Accueil", "/", class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if client_signed_in? %>
          <li class="nav-item">
            <%= link_to "Hi, #{current_client.email}", "#", class: "nav-link disabled" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mes réservations", reservation_history_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Déconnexion", destroy_client_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Connexion", new_client_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Inscription", new_client_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <%= yield %>
  </body>
</html>

app/views/reservation/history.html.erb
<h1>Your Reservations</h1>

<table>
  <thead>
  <tr>
    <th>PNR</th>
    <th>Flight</th>
    <th>Category</th>
    <th>Seats</th>
    <th>Departure airport</th>
    <th>Arrival airport</th>
    <th>Departure date</th>
    <th>Flight duration</th>
  </tr>
  </thead>
  <tbody>
  <% @reservations.each do |reservation| %>
    <tr>
      <td><%= link_to reservation.pnr, reservations_path(reservation) %></td>
      <td><%= reservation.flight.flight_company_id %></td>
      <td><%= reservation.category_name%></td>
      <td><%= reservation.nb_seats %></td>
      <td><%= reservation.flight.departure_airport.name %> ( <%= reservation.flight.departure_airport.iata %> )</td>
      <td><%= reservation.flight.arrival_airport.name %> ( <%= reservation.flight.arrival_airport.iata %> )</td>
      <td><%= reservation.flight.departure.strftime("%Y-%m-%d %H:%M") %></td>
      <td><%= reservation.flight.arrival.strftime("%Y-%m-%d %H:%M") %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/reservation/new.html.erb
<p class="card-text">
  Departure Airport: <%= @flight.departure_airport.name %> (<%= @flight.departure_airport.iata %>)<br>
  Arrival Airport: <%= @flight.arrival_airport.name %> (<%= @flight.arrival_airport.iata %>)<br>
  Departure Date and Hour: <%= @flight.departure.strftime('%Y-%m-%d %H:%M') %><br>
  Arrival Date and Hour: <%= (@flight.departure + @flight.duration.minutes).strftime('%Y-%m-%d %H:%M') %>
</p>
<%= form_with model: @reservation, url: :new_reservation_creation, method: :post, local: true do |form| %>
  <%= form.hidden_field :flight_id, value: @flight.id %>
  <!-- Add other reservation fields here -->
  <%= form.radio_button :category, "1", checked: true, id: "second" %>
  <%= form.label :seat_category_second, "Seconde Classe", for: "second" %>
  <%= form.radio_button :category, "0", id: "first" %>
  <%= form.label :seat_category_first, "Premiere Classe", for: "first" %>
  <%= form.number_field :nb_seats, min: 1, max: 99, step: 1, value: 1 %>
  <%= form.submit 'Submit Reservation', class: 'btn btn-primary' %>
<% end %>

app/views/reservation/old.erb
<%= form_with url: create_reservation_path, method: :post, local: true do |f| %>
  <div class="form-group">
    <%= f.label :flight_id, "Select Flight" %>
    <%= f.select :flight_id, options_from_collection_for_select(Flight.where('departure > ?', Time.now), :id, :flight_number), {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :seat_type, "Seat Type" %>
    <%= f.select :seat_type, options_for_select([['Economic', 'economic'], ['Business', 'business']]), {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :passengers, "Number of Passengers" %>
    <%= f.number_field :passengers, min: 1, max: 99, class: "form-control" %>
  </div>
  <%= f.submit 'Create Reservation', class: 'btn btn-primary' %>
<% end %>

app/views/reservation/success.html.erb
<h1>Reservation Successful</h1>
<p>Your reservation has been created with reference: <%= @reservation.pnr %></p>
<%= form_tag({controller: "reservation", action: "delete"}, method: "post") do %>
  <%= hidden_field_tag :id, @reservation.id %>
  <%= hidden_field_tag '_method', 'delete' %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= submit_tag "Delete Reservation", class: "btn btn-danger" %>
<% end %>